name: hello-world
on: push
jobs:
  get-job: 
  outputs:
       envId: ${{steps.getid.outputs.envId}}
       runs-on: ubuntu-latest
       steps:
       run: |
             envId=260
             echo "::set-output name=envId::($envId)"
my-job:
    runs-on: ubuntu-latest
    needs: [get-job]
    steps:
      - name: my-step
        run: |
             echo https://api.boomi.com/api/rest/v1/EnvironmentExtensions/${{needs.get-job.outputs.envId}}
    
            
