name: Create File

on:
  push:
    branches: [main]

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Directory
        run: mkdir -p my_files

      - name: Create File
        run: echo "Hello, world!" > my_files/hello.txt
