name: Create File

on:
  push:
    branches: [main]

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: |
          mkdir -p my_files
          echo "Hello, world!" > my_files/hello.txt
        shell: bash
