name: Create File
on:
  push
jobs:
 create_file:
   runs-on: ubuntu-latest
   steps:
   - name: get value
     run : |
         file="test"
         new_value=$file.json
         echo $new_value
                               
