name: Create File
on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
     - name: Extract Filename
       run: |
         fileToRead=./boomi/DeploymentConfiguration/ExtensionsUpdateConfiguration/ProjectDetails.DPP.json
          echo "Original path: $fileToRead"
          arrIN=(${fileToRead//// })
          echo "Array contents: ${arrIN[@]}"
          fileToRead=$(echo ${arrIN[5]})
          echo "Filename is: $fileToRead"
