name: hello-world
'on': push
jobs:
get-job: 
runs-on: ubuntu-latest
outputs:
       envId: ${{steps.getid.outputs.envId}}
steps:
run: |
     envId=260
     echo "::set-output name=envId::($envId)"
my-job:
    runs-on: ubuntu-latest
    needs: [get-job]
    steps:
      - name: my-step
        run: |
             envid="260"
             echo $envid
             echo https://api.boomi.com/api/rest/v1/EnvironmentExtensions/${{needs.get-job.outputs.envId}}
    
            
