name: Create File
on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: get value
        id: set_value
        run: |
          file={"name":"djaj"}
          result= $file | python -c "import sys, json; print(json.dumps(json.load(sys.stdin), indent=2))"
