name: Create File
on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: get value
        id: set_value
        run: |
          envId=d366c18f-94a1-4fab-9055-66994ba24219
          request='{
    "@type": "EnvironmentExtensions",
    "connections": {
        "@type": "Connections",
        "connection": [
            {
                "@type": "Connection",
                "field": [
                    {
                        "@type": "Field",
                        "id": "url",
                        "encryptedValueSet": false,
                        "usesEncryption": false,
                        "value": "https://console.convex-insurance.test.ataccama.online:442",
                        "componentOverride": false,
                        "useDefault": false
                    }
                ],
                "id": "70cf13bc-5c8d-416a-9be2-f6e0d19e68c3",
                "name": "[Atacamma] Party connection"
            }
        ]
    },
    "environmentId": "d366c18f-94a1-4fab-9055-66994ba24219",
    "extensionGroupId": "",
    "id": "d366c18f-94a1-4fab-9055-66994ba24219",
    "partial": true
}'
          CODE=$(curl -X POST \
                              -H "Authorization:BOOMI_TOKEN.ashmita.sawant@convexin.com:3501e989-7851-4620-9948-cd2d7924b7b7 " \
                              -H "Accept: application/json" \
                              -H "Content-Type: application/json" \
                              -d "$request" \
                              https://api.boomi.com/api/rest/v1/convexukserviceslimited-WN9RSJ/EnvironmentExtensions/$envId/update)
             echo "The response is : $CODE"
          echo $CODE
