name: Create File
on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
     - name: Extract Filename
       run: |
          fileToRead="./boomi/DeploymentConfiguration/ExtensionsUpdateConfiguration/ProjectDetails.DPP.json"
          filename=$(basename "$fileToRead")
          echo "Filename is: $filename"
