name: Create File
on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: get value
        id: set_value
        run: |
          envId=1234
          CODE=$(curl -X POST \
                              -H "Accept: application/json" \
                              -H "Content-Type: application/json" \
                              -d "$request" \
                              https://api.boomi.com/api/rest/v1/EnvironmentExtensions/$envId/update)
          echo $CODE
